server:
  port: 8888
  servlet:
    context-path: /

spring:
   freemarker:
      suffix: .ftl
  #    templateEncoding: UTF-8
      templateLoaderPath: classpath:/templates/
      charset: UTF-8
      content-type: text/html;charset=UTF-8
  #    default_encoding: UTF-8
      cache: false
      expose-session-attributes: true
      # 设置上下文路径
      request-context-attribute: request